### PR TITLE
Update es.xml

### PR DESCRIPTION
**Pull request by DalveenLeandor**
I didn't know if lines from 102 to 188 must be translated.

### CODE REVIEW

**Comment by dymanoid** [comment]
Yes, these lines need to be translated too... A lot of work, I know. Do you want to translate them, or we leave the English text?

**Comment by DalveenLeandor** [comment]
i will translate them, but i never seen that lines in game playing with ur mod, where they are? i ask cos i wana know what im translating to use most acurated spanish expresions.

**Comment by dymanoid** [comment]
These are mostly the information entries for different statistics, like e.g. the public transport stats.

**Comment by DalveenLeandor** [comment]
ok, i will play this night and look for it to make a good translation, u can cancel this pull request, i will do another when i finish. (tomorrow probably)

**Pull request closed without merging**
